### ISSUE TITLE
Just need Comments so that newcomers can understand the code instead of copying and pasting

### ISSUE THREAD

**Issue by deshwalmahesh** [tuvovan/Vision_Transformer_Keras#2]
I know a lot and I say a lot around 90% people like me who have this thing that they see code and feel intimidated. I just loved your code. It would have been surreal if you could add comments to line why some line is there and what is it working. I know it'll take some time but newcomers will remember you, for a long long time. [You can check this code here](https://www.kaggle.com/deshwalmahesh/bengali-ai-complete-beginner-tutorial-95-acc). People can come and see the work and actually learn rather than feeling intimidated and copy paste the whole code. Just a suggestion and a request.

**Comment by tuvovan** [comment]
thank you for your suggestion!
